language: c
services:
- docker
env:
  global:
  - PINS="imandra-prelude:."
  - DISTRO="ubuntu-16.04"

matrix:
  include:
  - language: node_js
    node_js: 11
    script: npm ci && npm run build
  - env: PACKAGE="imandra-prelude" OCAML_VERSION="4.03"
    install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
    script: bash -ex .travis-docker.sh
  - env: PACKAGE="imandra-prelude" OCAML_VERSION="4.04"
    install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
    script: bash -ex .travis-docker.sh
  - env: PACKAGE="imandra-prelude" OCAML_VERSION="4.05"
    install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
    script: bash -ex .travis-docker.sh
  - env: PACKAGE="imandra-prelude" OCAML_VERSION="4.06"
    install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
    script: bash -ex .travis-docker.sh
  - env: PACKAGE="imandra-prelude" OCAML_VERSION="4.07"
    install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
    script: bash -ex .travis-docker.sh
